Project/RecruitmentProcessWorkflow/RecruitementProcessClient/Models/RecruitmentStep.cs
using System.ComponentModel.DataAnnotations;

namespace RecruitmentProcessClient.Models
{
    public class RecruitmentStep
    {
        public int Id { get; set; }

        [Required]
        [Display(Name ="Workflow Name")]
        public string Description { get; set; }
        [Display(Name ="Is Active")]
        public bool IsActive { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Only positive numbers are allowed")]
        [Required]
        [Display(Name = "Sequence no")]
        public int OrderNo { get; set; }
    }
}

Project/RecruitmentProcessWorkflow/RecruitementProcessClient/Controllers/RecruitmentController.cs
using Newtonsoft.Json;
using RecruitementProcessClient.Util;
using RecruitmentProcessClient.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace RecruitmentProcessClient.Controllers
{
    public class RecruitmentController : Controller
    {
        private readonly string baseAddress = ConfigurationManager.AppSettings["BaseAddress"];
        public ActionResult Index()
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseAddress);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("applications/json"));
                var response = client.GetAsync("api/workflow/get").Result;
                if (response.IsSuccessStatusCode)
                {
                    IEnumerable<RecruitmentStep> steps = JsonConvert
                                                            .DeserializeObject<IEnumerable<RecruitmentStep>>
                                                                    (response.Content.ReadAsStringAsync().Result)
                                                                    .Where(r => r.IsActive);
                    return View(steps);
                }
                else
                {
                    return View(HttpStatusCode.BadRequest);
                }
            }
        }

        public ActionResult Recruitment(int id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseAddress);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("applications/json"));
                var response = client.GetAsync("api/workflow/get/" + id.ToString()).Result;
                if (response.IsSuccessStatusCode)
                {
                    RecruitmentStep step = JsonConvert
                                            .DeserializeObject<RecruitmentStep>
                                                (response.Content.ReadAsStringAsync().Result);

                    return View("Update", step);
                }
                else
                {
                    return View(HttpStatusCode.BadRequest);
                }
            }
        }

        public async Task<ActionResult> Update(RecruitmentStep recruitmentStep)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(baseAddress);
                    client.DefaultRequestHeaders.Accept.Clear();
                    var content = new StringContent(JsonConvert.SerializeObject(recruitmentStep),
                                                                        Encoding.UTF8, "application/Json");
                    var responseMessage = await client.PostAsync("api/workflow/update", content);
                    responseMessage.EnsureSuccessStatusCode();

                    if (responseMessage.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["Error"] = ErrorData.GetError(null, false);

                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = ErrorData.GetError(ex.Message);
            }

            return View();
        }

        public ActionResult Add()
        {
            return View();
        }

        public async Task<ActionResult> Save(RecruitmentStep recruitmentStep)
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(baseAddress);
                    client.DefaultRequestHeaders.Accept.Clear();
                    var content = new StringContent(JsonConvert.SerializeObject(recruitmentStep),
                                                                        Encoding.UTF8, "application/Json");
                    var responseMessage = await client.PostAsync("api/workflow/save", content);
                    responseMessage.EnsureSuccessStatusCode();

                    if (responseMessage.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["Error"] = ErrorData.GetError(null, false);

                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = ErrorData.GetError(ex.Message);
            }

            return View("Add");
        }

        public ActionResult ViewProcess()
        {
            return View();
        }

        public JsonResult Get(string applicantNo)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseAddress);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("applications/json"));
                var response = client.GetAsync("api/recruitment/get/" + applicantNo).Result;

                if (response.IsSuccessStatusCode)
                {
                    var obj = response.Content.ReadAsStringAsync().Result;
                    return Json(obj, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { Error = "Error", message = "Bad Request" });
                }

            }
        }
    }
}

Project/RecruitmentProcessWorkflow/RecruitementProcessClient/Controllers/WorkflowController.cs
using Newtonsoft.Json;
using RecruitmentProcessClient.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Mvc;

namespace RecruitmentProcessClient.Controllers
{
    public class WorkflowController : Controller
    {

        private readonly string baseAddress = ConfigurationManager.AppSettings["BaseAddress"];

        public ActionResult Index()
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseAddress);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("applications/json"));
                var response = client.GetAsync("api/workflow/get").Result;
                if (response.IsSuccessStatusCode)
                {
                    IEnumerable<RecruitmentStep> steps = JsonConvert
                                                            .DeserializeObject<IEnumerable<RecruitmentStep>>
                                                                    (response.Content.ReadAsStringAsync().Result);
                    return View(steps);
                }
                else
                {
                    return View(HttpStatusCode.BadRequest);
                }
            }
        }
    }
}

Project/RecruitmentProcessWorkflow/RecruitementProcessClient/Views/Recruitment/Add.cshtml
@model RecruitmentProcessClient.Models.RecruitmentStep


<h3>Add Process</h3>


@using (Html.BeginForm("Save", "Recruitment", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "chkBox" } })
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<span class="error-message">
    @TempData["Error"]
</span>

<br />
<br />
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<link href="~/Content/recruitment.css" rel="stylesheet" />

Project/RecruitmentProcessWorkflow/RecruitementProcessClient/Views/Recruitment/Index.cshtml
@model IEnumerable<RecruitmentProcessClient.Models.RecruitmentStep>

@{
    ViewBag.Title = "Process Workflow";
}

<h4>Recruitement Workflow</h4>

<p>
    @Html.ActionLink("New Workflow", "Add")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderNo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderNo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Recruitment", new { id = item.Id })
            </td>
        </tr>
    }

</table>
@Styles.Render("~/Content/recruitment.css")

Project/RecruitmentProcessWorkflow/RecruitementProcessClient/Views/Recruitment/Recruitment.cshtml
@model RecruitmentProcessClient.Models.RecruitmentStep

@{
    ViewBag.Title = "Edit Process";
}

<h4>Edit Process</h4>


@using (Html.BeginForm("Update", "Recruitment",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { @class = "chkBox" } })
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/RecruitmentProcessWorkflow/RecruitementProcessClient/Views/Recruitment/Update.cshtml
@model RecruitmentProcessClient.Models.RecruitmentStep

@{
    ViewBag.Title = "Edit Process";
}

<h3>Edit Workflow</h3>



@using (Html.BeginForm("Update", "Recruitment", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.IsActive, new { htmlAttributes = new { @class = "chkBox" } })
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OrderNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OrderNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<span class="error-message">
    @TempData["Error"]
</span>

<br />
<br />
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@Styles.Render("~/Content/recruitment.css")

Project/RecruitmentProcessWorkflow/RecruitementProcessClient/Views/Recruitment/ViewProcess.cshtml
@{
    ViewBag.Title = "Applicant Status";
}

<h4>Applicant Status</h4>
<div style="margin-top:20px">
    <input type="text" placeholder="Enter Applicant No" id="txtApplicantNo" />
    <input type="submit" id="btnSubmit" value="Search" />
</div>

<div id="tblData" class="result" style="margin-top :30px">
    <table id="tblResult" class="table" style="display:none">
        <thead>
            <tr>
                <th>Workflow Name</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
<div id="tblNoData" class="result" style="display:none;">
    <h4>No data to display</h4>
</div>

@section Scripts {
    @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
    @Scripts.Render("~/Scripts/recruitment.js")
}

Project/RecruitmentProcessWorkflow/RecruitementProcessClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Recruitment Process", "Index", "Recruitment", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("| Status", "ViewProcess", "Recruitment", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("| Workflows", "Index", "Workflow", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Recruitment Workflow Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Project/RecruitmentProcessWorkflow/RecruitementProcessClient/Views/Workflow/Index.cshtml
@model IEnumerable<RecruitmentProcessClient.Models.RecruitmentStep>

@{
    ViewBag.Title = "Workflows";
}


<h4>Workflows</h4>

<p>
    @Html.ActionLink("New Workflow", "Add", "Recruitment", null, null)
</p>
<table class="table" id="tbl">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderNo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderNo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Recruitment", "Recruitment", new { id = item.Id }, null)
            </td>
        </tr>
    }

</table>

@Styles.Render("~/Content/recruitment.css")